# NOTE: This file is auto generated by OpenAPI Generator 7.3.0-SNAPSHOT (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule FinnhubAPI.Model.AggregateIndicators do
  @moduledoc """

  """

  @derive Jason.Encoder
  defstruct [
    :technicalAnalysis,
    :trend
  ]

  @type t :: %__MODULE__{
          :technicalAnalysis => FinnhubAPI.Model.TechnicalAnalysis.t() | nil,
          :trend => FinnhubAPI.Model.Trend.t() | nil
        }

  alias FinnhubAPI.Deserializer

  def decode(value) do
    value
    |> Deserializer.deserialize(:technicalAnalysis, :struct, FinnhubAPI.Model.TechnicalAnalysis)
    |> Deserializer.deserialize(:trend, :struct, FinnhubAPI.Model.Trend)
  end
end
