# NOTE: This file is auto generated by OpenAPI Generator 7.3.0-SNAPSHOT (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule FinnhubAPI.Model.BondYieldCurveInfo do
  @moduledoc """

  """

  @derive Jason.Encoder
  defstruct [
    :d,
    :v
  ]

  @type t :: %__MODULE__{
          :d => String.t() | nil,
          :v => float() | nil
        }

  def decode(value) do
    value
  end
end
