# NOTE: This file is auto generated by OpenAPI Generator 7.3.0-SNAPSHOT (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule FinnhubAPI.Model.BreakdownItem do
  @moduledoc """

  """

  @derive Jason.Encoder
  defstruct [
    :accessNumber,
    :breakdown
  ]

  @type t :: %__MODULE__{
          :accessNumber => String.t() | nil,
          :breakdown => map() | nil
        }

  def decode(value) do
    value
  end
end
