# NOTE: This file is auto generated by OpenAPI Generator 7.3.0-SNAPSHOT (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule FinnhubAPI.Model.CompanyEarningsQualityScoreData do
  @moduledoc """

  """

  @derive Jason.Encoder
  defstruct [
    :period,
    :growth,
    :profitability,
    :cashGenerationCapitalAllocation,
    :leverage,
    :score,
    :letterScore
  ]

  @type t :: %__MODULE__{
          :period => String.t() | nil,
          :growth => float() | nil,
          :profitability => float() | nil,
          :cashGenerationCapitalAllocation => float() | nil,
          :leverage => float() | nil,
          :score => float() | nil,
          :letterScore => String.t() | nil
        }

  def decode(value) do
    value
  end
end
