# NOTE: This file is auto generated by OpenAPI Generator 7.3.0-SNAPSHOT (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule FinnhubAPI.Model.Company do
  @moduledoc """

  """

  @derive Jason.Encoder
  defstruct [
    :name,
    :age,
    :title,
    :since,
    :sex,
    :compensation,
    :currency
  ]

  @type t :: %__MODULE__{
          :name => String.t() | nil,
          :age => integer() | nil,
          :title => String.t() | nil,
          :since => String.t() | nil,
          :sex => String.t() | nil,
          :compensation => integer() | nil,
          :currency => String.t() | nil
        }

  def decode(value) do
    value
  end
end
