# NOTE: This file is auto generated by OpenAPI Generator 7.3.0-SNAPSHOT (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule FinnhubAPI.Model.CompanyNewsStatistics do
  @moduledoc """

  """

  @derive Jason.Encoder
  defstruct [
    :articlesInLastWeek,
    :buzz,
    :weeklyAverage
  ]

  @type t :: %__MODULE__{
          :articlesInLastWeek => integer() | nil,
          :buzz => float() | nil,
          :weeklyAverage => float() | nil
        }

  def decode(value) do
    value
  end
end
