# NOTE: This file is auto generated by OpenAPI Generator 7.3.0-SNAPSHOT (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule FinnhubAPI.Model.CompanyProfile2 do
  @moduledoc """

  """

  @derive Jason.Encoder
  defstruct [
    :country,
    :currency,
    :exchange,
    :name,
    :ticker,
    :ipo,
    :marketCapitalization,
    :shareOutstanding,
    :logo,
    :phone,
    :weburl,
    :finnhubIndustry
  ]

  @type t :: %__MODULE__{
          :country => String.t() | nil,
          :currency => String.t() | nil,
          :exchange => String.t() | nil,
          :name => String.t() | nil,
          :ticker => String.t() | nil,
          :ipo => Date.t() | nil,
          :marketCapitalization => float() | nil,
          :shareOutstanding => float() | nil,
          :logo => String.t() | nil,
          :phone => String.t() | nil,
          :weburl => String.t() | nil,
          :finnhubIndustry => String.t() | nil
        }

  alias FinnhubAPI.Deserializer

  def decode(value) do
    value
    |> Deserializer.deserialize(:ipo, :date, nil)
  end
end
