# NOTE: This file is auto generated by OpenAPI Generator 7.3.0-SNAPSHOT (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule FinnhubAPI.Model.CompanyExecutive do
  @moduledoc """

  """

  @derive Jason.Encoder
  defstruct [
    :symbol,
    :executive
  ]

  @type t :: %__MODULE__{
          :symbol => String.t() | nil,
          :executive => [FinnhubAPI.Model.Company.t()] | nil
        }

  alias FinnhubAPI.Deserializer

  def decode(value) do
    value
    |> Deserializer.deserialize(:executive, :list, FinnhubAPI.Model.Company)
  end
end
