# NOTE: This file is auto generated by OpenAPI Generator 7.3.0-SNAPSHOT (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule FinnhubAPI.Model.CongressionalTransaction do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :amountFrom,
    :amountTo,
    :assetName,
    :filingDate,
    :name,
    :ownerType,
    :position,
    :symbol,
    :transactionDate,
    :transactionType
  ]

  @type t :: %__MODULE__{
    :amountFrom => float() | nil,
    :amountTo => float() | nil,
    :assetName => String.t | nil,
    :filingDate => String.t | nil,
    :name => String.t | nil,
    :ownerType => String.t | nil,
    :position => String.t | nil,
    :symbol => String.t | nil,
    :transactionDate => String.t | nil,
    :transactionType => String.t | nil
  }

  def decode(value) do
    value
  end
end

