# NOTE: This file is auto generated by OpenAPI Generator 7.3.0-SNAPSHOT (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule FinnhubAPI.Model.CountryMetadata do
  @moduledoc """

  """

  @derive Jason.Encoder
  defstruct [
    :country,
    :code2,
    :code3,
    :codeNo,
    :currency,
    :currencyCode,
    :region,
    :subRegion,
    :rating,
    :defaultSpread,
    :countryRiskPremium,
    :equityRiskPremium
  ]

  @type t :: %__MODULE__{
          :country => String.t() | nil,
          :code2 => String.t() | nil,
          :code3 => String.t() | nil,
          :codeNo => String.t() | nil,
          :currency => String.t() | nil,
          :currencyCode => String.t() | nil,
          :region => String.t() | nil,
          :subRegion => String.t() | nil,
          :rating => String.t() | nil,
          :defaultSpread => float() | nil,
          :countryRiskPremium => float() | nil,
          :equityRiskPremium => float() | nil
        }

  def decode(value) do
    value
  end
end
