# NOTE: This file is auto generated by OpenAPI Generator 7.3.0-SNAPSHOT (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule FinnhubAPI.Model.CryptoSymbol do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :description,
    :displaySymbol,
    :symbol
  ]

  @type t :: %__MODULE__{
    :description => String.t | nil,
    :displaySymbol => String.t | nil,
    :symbol => String.t | nil
  }

  def decode(value) do
    value
  end
end

