# NOTE: This file is auto generated by OpenAPI Generator 7.3.0-SNAPSHOT (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule FinnhubAPI.Model.Dividends do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :symbol,
    :date,
    :amount,
    :adjustedAmount,
    :payDate,
    :recordDate,
    :declarationDate,
    :currency,
    :freq
  ]

  @type t :: %__MODULE__{
    :symbol => String.t | nil,
    :date => Date.t | nil,
    :amount => float() | nil,
    :adjustedAmount => float() | nil,
    :payDate => Date.t | nil,
    :recordDate => Date.t | nil,
    :declarationDate => Date.t | nil,
    :currency => String.t | nil,
    :freq => String.t | nil
  }

  alias FinnhubAPI.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:date, :date, nil)
     |> Deserializer.deserialize(:payDate, :date, nil)
     |> Deserializer.deserialize(:recordDate, :date, nil)
     |> Deserializer.deserialize(:declarationDate, :date, nil)
  end
end

