# NOTE: This file is auto generated by OpenAPI Generator 7.3.0-SNAPSHOT (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule FinnhubAPI.Model.EarningsCallTranscriptsList do
  @moduledoc """

  """

  @derive Jason.Encoder
  defstruct [
    :symbol,
    :transcripts
  ]

  @type t :: %__MODULE__{
          :symbol => String.t() | nil,
          :transcripts => [FinnhubAPI.Model.StockTranscripts.t()] | nil
        }

  alias FinnhubAPI.Deserializer

  def decode(value) do
    value
    |> Deserializer.deserialize(:transcripts, :list, FinnhubAPI.Model.StockTranscripts)
  end
end
