# NOTE: This file is auto generated by OpenAPI Generator 7.3.0-SNAPSHOT (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule FinnhubAPI.Model.EarningsCalendar do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :earningsCalendar
  ]

  @type t :: %__MODULE__{
    :earningsCalendar => [FinnhubAPI.Model.EarningRelease.t] | nil
  }

  alias FinnhubAPI.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:earningsCalendar, :list, FinnhubAPI.Model.EarningRelease)
  end
end

