# NOTE: This file is auto generated by OpenAPI Generator 7.3.0-SNAPSHOT (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule FinnhubAPI.Model.EarningsCallTranscripts do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :symbol,
    :transcript,
    :participant,
    :audio,
    :id,
    :title,
    :time,
    :year,
    :quarter
  ]

  @type t :: %__MODULE__{
    :symbol => String.t | nil,
    :transcript => [FinnhubAPI.Model.TranscriptContent.t] | nil,
    :participant => [FinnhubAPI.Model.TranscriptParticipant.t] | nil,
    :audio => String.t | nil,
    :id => String.t | nil,
    :title => String.t | nil,
    :time => String.t | nil,
    :year => integer() | nil,
    :quarter => integer() | nil
  }

  alias FinnhubAPI.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:transcript, :list, FinnhubAPI.Model.TranscriptContent)
     |> Deserializer.deserialize(:participant, :list, FinnhubAPI.Model.TranscriptParticipant)
  end
end

