# NOTE: This file is auto generated by OpenAPI Generator 7.3.0-SNAPSHOT (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule FinnhubAPI.Model.EconomicEvent do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :actual,
    :prev,
    :country,
    :unit,
    :estimate,
    :event,
    :impact,
    :time
  ]

  @type t :: %__MODULE__{
    :actual => float() | nil,
    :prev => float() | nil,
    :country => String.t | nil,
    :unit => String.t | nil,
    :estimate => float() | nil,
    :event => String.t | nil,
    :impact => String.t | nil,
    :time => String.t | nil
  }

  def decode(value) do
    value
  end
end

