# NOTE: This file is auto generated by OpenAPI Generator 7.3.0-SNAPSHOT (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule FinnhubAPI.Model.EconomicData do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :data,
    :code
  ]

  @type t :: %__MODULE__{
    :data => [FinnhubAPI.Model.EconomicDataInfo.t] | nil,
    :code => String.t | nil
  }

  alias FinnhubAPI.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:data, :list, FinnhubAPI.Model.EconomicDataInfo)
  end
end

