# NOTE: This file is auto generated by OpenAPI Generator 7.3.0-SNAPSHOT (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule FinnhubAPI.Model.EtfSectorExposureData do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :industry,
    :exposure
  ]

  @type t :: %__MODULE__{
    :industry => String.t | nil,
    :exposure => float() | nil
  }

  def decode(value) do
    value
  end
end

