# NOTE: This file is auto generated by OpenAPI Generator 7.3.0-SNAPSHOT (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule FinnhubAPI.Model.EtfsProfile do
  @moduledoc """

  """

  @derive Jason.Encoder
  defstruct [
    :symbol,
    :profile
  ]

  @type t :: %__MODULE__{
          :symbol => String.t() | nil,
          :profile => FinnhubAPI.Model.EtfProfileData.t() | nil
        }

  alias FinnhubAPI.Deserializer

  def decode(value) do
    value
    |> Deserializer.deserialize(:profile, :struct, FinnhubAPI.Model.EtfProfileData)
  end
end
