# NOTE: This file is auto generated by OpenAPI Generator 7.3.0-SNAPSHOT (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule FinnhubAPI.Model.EtfsSectorExposure do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :symbol,
    :sectorExposure
  ]

  @type t :: %__MODULE__{
    :symbol => String.t | nil,
    :sectorExposure => [FinnhubAPI.Model.EtfSectorExposureData.t] | nil
  }

  alias FinnhubAPI.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:sectorExposure, :list, FinnhubAPI.Model.EtfSectorExposureData)
  end
end

