# NOTE: This file is auto generated by OpenAPI Generator 7.3.0-SNAPSHOT (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule FinnhubAPI.Model.EtfsHoldings do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :symbol,
    :atDate,
    :numberOfHoldings,
    :holdings
  ]

  @type t :: %__MODULE__{
    :symbol => String.t | nil,
    :atDate => Date.t | nil,
    :numberOfHoldings => integer() | nil,
    :holdings => [FinnhubAPI.Model.EtfHoldingsData.t] | nil
  }

  alias FinnhubAPI.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:atDate, :date, nil)
     |> Deserializer.deserialize(:holdings, :list, FinnhubAPI.Model.EtfHoldingsData)
  end
end

