# NOTE: This file is auto generated by OpenAPI Generator 7.3.0-SNAPSHOT (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule FinnhubAPI.Model.ExcerptResponse do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :content,
    :snippetId,
    :startOffset,
    :endOffset
  ]

  @type t :: %__MODULE__{
    :content => String.t | nil,
    :snippetId => String.t | nil,
    :startOffset => String.t | nil,
    :endOffset => String.t | nil
  }

  def decode(value) do
    value
  end
end

