# NOTE: This file is auto generated by OpenAPI Generator 7.3.0-SNAPSHOT (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule FinnhubAPI.Model.FdaComitteeMeeting do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :fromDate,
    :toDate,
    :eventDescription,
    :url
  ]

  @type t :: %__MODULE__{
    :fromDate => String.t | nil,
    :toDate => String.t | nil,
    :eventDescription => String.t | nil,
    :url => String.t | nil
  }

  def decode(value) do
    value
  end
end

