# NOTE: This file is auto generated by OpenAPI Generator 7.3.0-SNAPSHOT (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule FinnhubAPI.Model.Filing do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :accessNumber,
    :symbol,
    :cik,
    :form,
    :filedDate,
    :acceptedDate,
    :reportUrl,
    :filingUrl
  ]

  @type t :: %__MODULE__{
    :accessNumber => String.t | nil,
    :symbol => String.t | nil,
    :cik => String.t | nil,
    :form => String.t | nil,
    :filedDate => String.t | nil,
    :acceptedDate => String.t | nil,
    :reportUrl => String.t | nil,
    :filingUrl => String.t | nil
  }

  def decode(value) do
    value
  end
end

