# NOTE: This file is auto generated by OpenAPI Generator 7.3.0-SNAPSHOT (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule FinnhubAPI.Model.FilingSentiment do
  @moduledoc """

  """

  @derive Jason.Encoder
  defstruct [
    :negative,
    :positive,
    :polarity,
    :litigious,
    :uncertainty,
    :constraining,
    :"modal-weak",
    :"modal-strong",
    :"modal-moderate"
  ]

  @type t :: %__MODULE__{
          :negative => float() | nil,
          :positive => float() | nil,
          :polarity => float() | nil,
          :litigious => float() | nil,
          :uncertainty => float() | nil,
          :constraining => float() | nil,
          :"modal-weak" => float() | nil,
          :"modal-strong" => float() | nil,
          :"modal-moderate" => float() | nil
        }

  def decode(value) do
    value
  end
end
