# NOTE: This file is auto generated by OpenAPI Generator 7.3.0-SNAPSHOT (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule FinnhubAPI.Model.FilingResponse do
  @moduledoc """

  """

  @derive Jason.Encoder
  defstruct [
    :filingId,
    :title,
    :filerId,
    :symbol,
    :name,
    :acceptanceDate,
    :filedDate,
    :reportDate,
    :form,
    :amend,
    :source,
    :pageCount,
    :documentCount
  ]

  @type t :: %__MODULE__{
          :filingId => String.t() | nil,
          :title => String.t() | nil,
          :filerId => String.t() | nil,
          :symbol => map() | nil,
          :name => String.t() | nil,
          :acceptanceDate => String.t() | nil,
          :filedDate => String.t() | nil,
          :reportDate => String.t() | nil,
          :form => String.t() | nil,
          :amend => boolean() | nil,
          :source => String.t() | nil,
          :pageCount => integer() | nil,
          :documentCount => integer() | nil
        }

  def decode(value) do
    value
  end
end
