# NOTE: This file is auto generated by OpenAPI Generator 7.3.0-SNAPSHOT (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule FinnhubAPI.Model.HistoricalNbbo do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :s,
    :skip,
    :count,
    :total,
    :av,
    :a,
    :ax,
    :bv,
    :b,
    :bx,
    :t,
    :c
  ]

  @type t :: %__MODULE__{
    :s => String.t | nil,
    :skip => integer() | nil,
    :count => integer() | nil,
    :total => integer() | nil,
    :av => [float()] | nil,
    :a => [float()] | nil,
    :ax => [String.t] | nil,
    :bv => [float()] | nil,
    :b => [float()] | nil,
    :bx => [String.t] | nil,
    :t => [integer()] | nil,
    :c => [[String.t]] | nil
  }

  def decode(value) do
    value
  end
end

