# NOTE: This file is auto generated by OpenAPI Generator 7.3.0-SNAPSHOT (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule FinnhubAPI.Model.InFilingSearchBody do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :query,
    :filingId
  ]

  @type t :: %__MODULE__{
    :query => String.t,
    :filingId => String.t
  }

  def decode(value) do
    value
  end
end

