# NOTE: This file is auto generated by OpenAPI Generator 7.3.0-SNAPSHOT (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule FinnhubAPI.Model.IndicesHistoricalConstituents do
  @moduledoc """

  """

  @derive Jason.Encoder
  defstruct [
    :symbol,
    :historicalConstituents
  ]

  @type t :: %__MODULE__{
          :symbol => String.t() | nil,
          :historicalConstituents => [FinnhubAPI.Model.IndexHistoricalConstituent.t()] | nil
        }

  alias FinnhubAPI.Deserializer

  def decode(value) do
    value
    |> Deserializer.deserialize(
      :historicalConstituents,
      :list,
      FinnhubAPI.Model.IndexHistoricalConstituent
    )
  end
end
