# NOTE: This file is auto generated by OpenAPI Generator 7.3.0-SNAPSHOT (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule FinnhubAPI.Model.IndicesConstituents do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :symbol,
    :constituents,
    :constituentsBreakdown
  ]

  @type t :: %__MODULE__{
    :symbol => String.t | nil,
    :constituents => [String.t] | nil,
    :constituentsBreakdown => [FinnhubAPI.Model.IndicesConstituentsBreakdown.t] | nil
  }

  alias FinnhubAPI.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:constituentsBreakdown, :list, FinnhubAPI.Model.IndicesConstituentsBreakdown)
  end
end

