# NOTE: This file is auto generated by OpenAPI Generator 7.3.0-SNAPSHOT (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule FinnhubAPI.Model.IndicesConstituentsBreakdown do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :symbol,
    :name,
    :isin,
    :cusip,
    :shareClassFIGI,
    :weight
  ]

  @type t :: %__MODULE__{
    :symbol => String.t | nil,
    :name => String.t | nil,
    :isin => String.t | nil,
    :cusip => String.t | nil,
    :shareClassFIGI => String.t | nil,
    :weight => float() | nil
  }

  def decode(value) do
    value
  end
end

