# NOTE: This file is auto generated by OpenAPI Generator 7.3.0-SNAPSHOT (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule FinnhubAPI.Model.Indicator do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :buy,
    :neutral,
    :sell
  ]

  @type t :: %__MODULE__{
    :buy => integer() | nil,
    :neutral => integer() | nil,
    :sell => integer() | nil
  }

  def decode(value) do
    value
  end
end

