# NOTE: This file is auto generated by OpenAPI Generator 7.3.0-SNAPSHOT (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule FinnhubAPI.Model.InsiderSentimentsData do
  @moduledoc """

  """

  @derive Jason.Encoder
  defstruct [
    :symbol,
    :year,
    :month,
    :change,
    :mspr
  ]

  @type t :: %__MODULE__{
          :symbol => String.t() | nil,
          :year => integer() | nil,
          :month => integer() | nil,
          :change => integer() | nil,
          :mspr => float() | nil
        }

  def decode(value) do
    value
  end
end
