# NOTE: This file is auto generated by OpenAPI Generator 7.3.0-SNAPSHOT (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule FinnhubAPI.Model.InstitutionalPortfolio do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :name,
    :cik,
    :data
  ]

  @type t :: %__MODULE__{
    :name => String.t | nil,
    :cik => String.t | nil,
    :data => [FinnhubAPI.Model.InstitutionalPortfolioGroup.t] | nil
  }

  alias FinnhubAPI.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:data, :list, FinnhubAPI.Model.InstitutionalPortfolioGroup)
  end
end

