# NOTE: This file is auto generated by OpenAPI Generator 7.3.0-SNAPSHOT (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule FinnhubAPI.Model.InstitutionalPortfolioGroup do
  @moduledoc """

  """

  @derive Jason.Encoder
  defstruct [
    :reportDate,
    :filingDate,
    :portfolio
  ]

  @type t :: %__MODULE__{
          :reportDate => String.t() | nil,
          :filingDate => String.t() | nil,
          :portfolio => [FinnhubAPI.Model.InstitutionalPortfolioInfo.t()] | nil
        }

  alias FinnhubAPI.Deserializer

  def decode(value) do
    value
    |> Deserializer.deserialize(:portfolio, :list, FinnhubAPI.Model.InstitutionalPortfolioInfo)
  end
end
