# NOTE: This file is auto generated by OpenAPI Generator 7.3.0-SNAPSHOT (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule FinnhubAPI.Model.InstitutionalPortfolioInfo do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :symbol,
    :cusip,
    :name,
    :putCall,
    :change,
    :noVoting,
    :percentage,
    :share,
    :sharedVoting,
    :soleVoting,
    :value
  ]

  @type t :: %__MODULE__{
    :symbol => String.t | nil,
    :cusip => String.t | nil,
    :name => String.t | nil,
    :putCall => String.t | nil,
    :change => float() | nil,
    :noVoting => float() | nil,
    :percentage => float() | nil,
    :share => float() | nil,
    :sharedVoting => float() | nil,
    :soleVoting => float() | nil,
    :value => float() | nil
  }

  def decode(value) do
    value
  end
end

