# NOTE: This file is auto generated by OpenAPI Generator 7.3.0-SNAPSHOT (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule FinnhubAPI.Model.InvestmentThemes do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :theme,
    :data
  ]

  @type t :: %__MODULE__{
    :theme => String.t | nil,
    :data => [FinnhubAPI.Model.InvestmentThemePortfolio.t] | nil
  }

  alias FinnhubAPI.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:data, :list, FinnhubAPI.Model.InvestmentThemePortfolio)
  end
end

