# NOTE: This file is auto generated by OpenAPI Generator 7.3.0-SNAPSHOT (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule FinnhubAPI.Model.IsinChangeInfo do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :atDate,
    :oldIsin,
    :newIsin
  ]

  @type t :: %__MODULE__{
    :atDate => String.t | nil,
    :oldIsin => String.t | nil,
    :newIsin => String.t | nil
  }

  def decode(value) do
    value
  end
end

