# NOTE: This file is auto generated by OpenAPI Generator 7.3.0-SNAPSHOT (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule FinnhubAPI.Model.LobbyingData do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :symbol,
    :name,
    :description,
    :country,
    :year,
    :period,
    :income,
    :expenses,
    :documentUrl,
    :postedName,
    :date,
    :clientId,
    :registrantId,
    :senateId,
    :houseregistrantId
  ]

  @type t :: %__MODULE__{
    :symbol => String.t | nil,
    :name => String.t | nil,
    :description => String.t | nil,
    :country => String.t | nil,
    :year => integer() | nil,
    :period => String.t | nil,
    :income => float() | nil,
    :expenses => float() | nil,
    :documentUrl => String.t | nil,
    :postedName => String.t | nil,
    :date => String.t | nil,
    :clientId => String.t | nil,
    :registrantId => String.t | nil,
    :senateId => String.t | nil,
    :houseregistrantId => String.t | nil
  }

  def decode(value) do
    value
  end
end

