# NOTE: This file is auto generated by OpenAPI Generator 7.3.0-SNAPSHOT (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule FinnhubAPI.Model.MarketStatus do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :exchange,
    :timezone,
    :session,
    :holiday,
    :isOpen,
    :t
  ]

  @type t :: %__MODULE__{
    :exchange => String.t | nil,
    :timezone => String.t | nil,
    :session => String.t | nil,
    :holiday => String.t | nil,
    :isOpen => boolean() | nil,
    :t => integer() | nil
  }

  def decode(value) do
    value
  end
end

