# NOTE: This file is auto generated by OpenAPI Generator 7.3.0-SNAPSHOT (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule FinnhubAPI.Model.MutualFundProfile do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :symbol,
    :profile
  ]

  @type t :: %__MODULE__{
    :symbol => String.t | nil,
    :profile => FinnhubAPI.Model.MutualFundProfileData.t | nil
  }

  alias FinnhubAPI.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:profile, :struct, FinnhubAPI.Model.MutualFundProfileData)
  end
end

