# NOTE: This file is auto generated by OpenAPI Generator 7.3.0-SNAPSHOT (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule FinnhubAPI.Model.MutualFundHoldingsData do
  @moduledoc """

  """

  @derive Jason.Encoder
  defstruct [
    :symbol,
    :name,
    :isin,
    :cusip,
    :share,
    :percent,
    :value,
    :assetType
  ]

  @type t :: %__MODULE__{
          :symbol => String.t() | nil,
          :name => String.t() | nil,
          :isin => String.t() | nil,
          :cusip => String.t() | nil,
          :share => float() | nil,
          :percent => float() | nil,
          :value => float() | nil,
          :assetType => String.t() | nil
        }

  def decode(value) do
    value
  end
end
