# NOTE: This file is auto generated by OpenAPI Generator 7.3.0-SNAPSHOT (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule FinnhubAPI.Model.MutualFundSectorExposure do
  @moduledoc """

  """

  @derive Jason.Encoder
  defstruct [
    :symbol,
    :sectorExposure
  ]

  @type t :: %__MODULE__{
          :symbol => String.t() | nil,
          :sectorExposure => [FinnhubAPI.Model.MutualFundSectorExposureData.t()] | nil
        }

  alias FinnhubAPI.Deserializer

  def decode(value) do
    value
    |> Deserializer.deserialize(
      :sectorExposure,
      :list,
      FinnhubAPI.Model.MutualFundSectorExposureData
    )
  end
end
