# NOTE: This file is auto generated by OpenAPI Generator 7.3.0-SNAPSHOT (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule FinnhubAPI.Model.PressRelease do
  @moduledoc """

  """

  @derive Jason.Encoder
  defstruct [
    :symbol,
    :majorDevelopment
  ]

  @type t :: %__MODULE__{
          :symbol => String.t() | nil,
          :majorDevelopment => [FinnhubAPI.Model.Development.t()] | nil
        }

  alias FinnhubAPI.Deserializer

  def decode(value) do
    value
    |> Deserializer.deserialize(:majorDevelopment, :list, FinnhubAPI.Model.Development)
  end
end
