# NOTE: This file is auto generated by OpenAPI Generator 7.3.0-SNAPSHOT (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule FinnhubAPI.Model.PriceMetrics do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :symbol,
    :atDate,
    :data
  ]

  @type t :: %__MODULE__{
    :symbol => String.t | nil,
    :atDate => String.t | nil,
    :data => map() | nil
  }

  def decode(value) do
    value
  end
end

