# NOTE: This file is auto generated by OpenAPI Generator 7.3.0-SNAPSHOT (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule FinnhubAPI.Model.Quote do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :o,
    :h,
    :l,
    :c,
    :pc,
    :d,
    :dp
  ]

  @type t :: %__MODULE__{
    :o => float() | nil,
    :h => float() | nil,
    :l => float() | nil,
    :c => float() | nil,
    :pc => float() | nil,
    :d => float() | nil,
    :dp => float() | nil
  }

  def decode(value) do
    value
  end
end

