# NOTE: This file is auto generated by OpenAPI Generator 7.3.0-SNAPSHOT (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule FinnhubAPI.Model.RecommendationTrend do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :symbol,
    :buy,
    :hold,
    :period,
    :sell,
    :strongBuy,
    :strongSell
  ]

  @type t :: %__MODULE__{
    :symbol => String.t | nil,
    :buy => integer() | nil,
    :hold => integer() | nil,
    :period => String.t | nil,
    :sell => integer() | nil,
    :strongBuy => integer() | nil,
    :strongSell => integer() | nil
  }

  def decode(value) do
    value
  end
end

