# NOTE: This file is auto generated by OpenAPI Generator 7.3.0-SNAPSHOT (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule FinnhubAPI.Model.Report do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :accessNumber,
    :symbol,
    :cik,
    :year,
    :quarter,
    :form,
    :startDate,
    :endDate,
    :filedDate,
    :acceptedDate,
    :report
  ]

  @type t :: %__MODULE__{
    :accessNumber => String.t | nil,
    :symbol => String.t | nil,
    :cik => String.t | nil,
    :year => integer() | nil,
    :quarter => integer() | nil,
    :form => String.t | nil,
    :startDate => String.t | nil,
    :endDate => String.t | nil,
    :filedDate => String.t | nil,
    :acceptedDate => String.t | nil,
    :report => map() | nil
  }

  def decode(value) do
    value
  end
end

