# NOTE: This file is auto generated by OpenAPI Generator 7.3.0-SNAPSHOT (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule FinnhubAPI.Model.SearchResponse do
  @moduledoc """

  """

  @derive Jason.Encoder
  defstruct [
    :count,
    :took,
    :page,
    :filings
  ]

  @type t :: %__MODULE__{
          :count => integer() | nil,
          :took => integer() | nil,
          :page => integer() | nil,
          :filings => [FinnhubAPI.Model.FilingResponse.t()] | nil
        }

  alias FinnhubAPI.Deserializer

  def decode(value) do
    value
    |> Deserializer.deserialize(:filings, :list, FinnhubAPI.Model.FilingResponse)
  end
end
