# NOTE: This file is auto generated by OpenAPI Generator 7.3.0-SNAPSHOT (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule FinnhubAPI.Model.Sentiment do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :bearishPercent,
    :bullishPercent
  ]

  @type t :: %__MODULE__{
    :bearishPercent => float() | nil,
    :bullishPercent => float() | nil
  }

  def decode(value) do
    value
  end
end

