# NOTE: This file is auto generated by OpenAPI Generator 7.3.0-SNAPSHOT (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule FinnhubAPI.Model.SimilarityIndexInfo do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :cik,
    :item1,
    :item1a,
    :item2,
    :item7,
    :item7a,
    :accessNumber,
    :form,
    :filedDate,
    :acceptedDate,
    :reportUrl,
    :filingUrl
  ]

  @type t :: %__MODULE__{
    :cik => String.t | nil,
    :item1 => float() | nil,
    :item1a => float() | nil,
    :item2 => float() | nil,
    :item7 => float() | nil,
    :item7a => float() | nil,
    :accessNumber => String.t | nil,
    :form => String.t | nil,
    :filedDate => String.t | nil,
    :acceptedDate => String.t | nil,
    :reportUrl => String.t | nil,
    :filingUrl => String.t | nil
  }

  def decode(value) do
    value
  end
end

