# NOTE: This file is auto generated by OpenAPI Generator 7.3.0-SNAPSHOT (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule FinnhubAPI.Model.SimilarityIndex do
  @moduledoc """

  """

  @derive Jason.Encoder
  defstruct [
    :symbol,
    :cik,
    :similarity
  ]

  @type t :: %__MODULE__{
          :symbol => String.t() | nil,
          :cik => String.t() | nil,
          :similarity => [FinnhubAPI.Model.SimilarityIndexInfo.t()] | nil
        }

  alias FinnhubAPI.Deserializer

  def decode(value) do
    value
    |> Deserializer.deserialize(:similarity, :list, FinnhubAPI.Model.SimilarityIndexInfo)
  end
end
