# NOTE: This file is auto generated by OpenAPI Generator 7.3.0-SNAPSHOT (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule FinnhubAPI.Model.Split do
  @moduledoc """

  """

  @derive Jason.Encoder
  defstruct [
    :symbol,
    :date,
    :fromFactor,
    :toFactor
  ]

  @type t :: %__MODULE__{
          :symbol => String.t() | nil,
          :date => Date.t() | nil,
          :fromFactor => float() | nil,
          :toFactor => float() | nil
        }

  alias FinnhubAPI.Deserializer

  def decode(value) do
    value
    |> Deserializer.deserialize(:date, :date, nil)
  end
end
