# NOTE: This file is auto generated by OpenAPI Generator 7.3.0-SNAPSHOT (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule FinnhubAPI.Model.StockSymbol do
  @moduledoc """

  """

  @derive Jason.Encoder
  defstruct [
    :description,
    :displaySymbol,
    :symbol,
    :type,
    :mic,
    :figi,
    :shareClassFIGI,
    :currency,
    :symbol2,
    :isin
  ]

  @type t :: %__MODULE__{
          :description => String.t() | nil,
          :displaySymbol => String.t() | nil,
          :symbol => String.t() | nil,
          :type => String.t() | nil,
          :mic => String.t() | nil,
          :figi => String.t() | nil,
          :shareClassFIGI => String.t() | nil,
          :currency => String.t() | nil,
          :symbol2 => String.t() | nil,
          :isin => String.t() | nil
        }

  def decode(value) do
    value
  end
end
