# NOTE: This file is auto generated by OpenAPI Generator 7.3.0-SNAPSHOT (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule FinnhubAPI.Model.SupportResistance do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :levels
  ]

  @type t :: %__MODULE__{
    :levels => [float()] | nil
  }

  def decode(value) do
    value
  end
end

