# NOTE: This file is auto generated by OpenAPI Generator 7.3.0-SNAPSHOT (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule FinnhubAPI.Model.SymbolChangeInfo do
  @moduledoc """

  """

  @derive Jason.Encoder
  defstruct [
    :atDate,
    :oldSymbol,
    :newSymbol
  ]

  @type t :: %__MODULE__{
          :atDate => String.t() | nil,
          :oldSymbol => String.t() | nil,
          :newSymbol => String.t() | nil
        }

  def decode(value) do
    value
  end
end
