# NOTE: This file is auto generated by OpenAPI Generator 7.3.0-SNAPSHOT (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule FinnhubAPI.Model.TechnicalAnalysis do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :count,
    :signal
  ]

  @type t :: %__MODULE__{
    :count => FinnhubAPI.Model.Indicator.t | nil,
    :signal => String.t | nil
  }

  alias FinnhubAPI.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:count, :struct, FinnhubAPI.Model.Indicator)
  end
end

