# NOTE: This file is auto generated by OpenAPI Generator 7.3.0-SNAPSHOT (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule FinnhubAPI.Model.TickData do
  @moduledoc """

  """

  @derive Jason.Encoder
  defstruct [
    :s,
    :skip,
    :count,
    :total,
    :v,
    :p,
    :t,
    :x,
    :c
  ]

  @type t :: %__MODULE__{
          :s => String.t() | nil,
          :skip => integer() | nil,
          :count => integer() | nil,
          :total => integer() | nil,
          :v => [float()] | nil,
          :p => [float()] | nil,
          :t => [integer()] | nil,
          :x => [String.t()] | nil,
          :c => [[String.t()]] | nil
        }

  def decode(value) do
    value
  end
end
