# NOTE: This file is auto generated by OpenAPI Generator 7.3.0-SNAPSHOT (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule FinnhubAPI.Model.TranscriptContent do
  @moduledoc """

  """

  @derive Jason.Encoder
  defstruct [
    :name,
    :speech,
    :session
  ]

  @type t :: %__MODULE__{
          :name => String.t() | nil,
          :speech => [String.t()] | nil,
          :session => String.t() | nil
        }

  def decode(value) do
    value
  end
end
