# NOTE: This file is auto generated by OpenAPI Generator 7.3.0-SNAPSHOT (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule FinnhubAPI.Model.Trend do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :adx,
    :trending
  ]

  @type t :: %__MODULE__{
    :adx => float() | nil,
    :trending => boolean() | nil
  }

  def decode(value) do
    value
  end
end

