# NOTE: This file is auto generated by OpenAPI Generator 7.3.0-SNAPSHOT (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule FinnhubAPI.Model.UpgradeDowngrade do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :symbol,
    :gradeTime,
    :fromGrade,
    :toGrade,
    :company,
    :action
  ]

  @type t :: %__MODULE__{
    :symbol => String.t | nil,
    :gradeTime => integer() | nil,
    :fromGrade => String.t | nil,
    :toGrade => String.t | nil,
    :company => String.t | nil,
    :action => String.t | nil
  }

  def decode(value) do
    value
  end
end

