# NOTE: This file is auto generated by OpenAPI Generator 7.3.0-SNAPSHOT (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule FinnhubAPI.Model.UsaSpending do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :symbol,
    :recipientName,
    :recipientParentName,
    :awardDescription,
    :country,
    :actionDate,
    :totalValue,
    :performanceStartDate,
    :performanceEndDate,
    :awardingAgencyName,
    :awardingSubAgencyName,
    :awardingOfficeName,
    :performanceCountry,
    :performanceCity,
    :performanceCounty,
    :performanceState,
    :performanceZipCode,
    :performanceCongressionalDistrict,
    :naicsCode,
    :permalink
  ]

  @type t :: %__MODULE__{
    :symbol => String.t | nil,
    :recipientName => String.t | nil,
    :recipientParentName => String.t | nil,
    :awardDescription => String.t | nil,
    :country => String.t | nil,
    :actionDate => String.t | nil,
    :totalValue => float() | nil,
    :performanceStartDate => String.t | nil,
    :performanceEndDate => String.t | nil,
    :awardingAgencyName => String.t | nil,
    :awardingSubAgencyName => String.t | nil,
    :awardingOfficeName => String.t | nil,
    :performanceCountry => String.t | nil,
    :performanceCity => String.t | nil,
    :performanceCounty => String.t | nil,
    :performanceState => String.t | nil,
    :performanceZipCode => String.t | nil,
    :performanceCongressionalDistrict => String.t | nil,
    :naicsCode => String.t | nil,
    :permalink => String.t | nil
  }

  def decode(value) do
    value
  end
end

