# NOTE: This file is auto generated by OpenAPI Generator 7.3.0-SNAPSHOT (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule FinnhubAPI.Model.UsptoPatent do
  @moduledoc """

  """

  @derive Jason.Encoder
  defstruct [
    :applicationNumber,
    :companyFilingName,
    :filingDate,
    :description,
    :filingStatus,
    :patentNumber,
    :publicationDate,
    :patentType,
    :url
  ]

  @type t :: %__MODULE__{
          :applicationNumber => String.t() | nil,
          :companyFilingName => [String.t()] | nil,
          :filingDate => String.t() | nil,
          :description => String.t() | nil,
          :filingStatus => String.t() | nil,
          :patentNumber => String.t() | nil,
          :publicationDate => String.t() | nil,
          :patentType => String.t() | nil,
          :url => String.t() | nil
        }

  def decode(value) do
    value
  end
end
